// Linux numbers, since the sandbox presents itself as linux.
export const SIGNALS: Record<string, number> = {
  SIGHUP: 1, SIGINT: 2, SIGQUIT: 3, SIGILL: 4, SIGTRAP: 5, SIGABRT: 6, SIGIOT: 6,
  SIGBUS: 7, SIGFPE: 8, SIGKILL: 9, SIGUSR1: 10, SIGSEGV: 11, SIGUSR2: 12,
  SIGPIPE: 13, SIGALRM: 14, SIGTERM: 15, SIGCHLD: 17, SIGSTKFLT: 16, SIGCONT: 18,
  SIGSTOP: 19, SIGTSTP: 20, SIGTTIN: 21, SIGTTOU: 22, SIGURG: 23, SIGXCPU: 24,
  SIGXFSZ: 25, SIGVTALRM: 26, SIGPROF: 27, SIGWINCH: 28, SIGIO: 29, SIGPOLL: 29,
  SIGPWR: 30, SIGSYS: 31,
};

export const ERRNO: Record<string, number> = {
  E2BIG: 7, EACCES: 13, EADDRINUSE: 98, EADDRNOTAVAIL: 99, EAGAIN: 11, EBADF: 9,
  EBUSY: 16, ECONNABORTED: 103, ECONNREFUSED: 111, ECONNRESET: 104, EEXIST: 17,
  EINVAL: 22, EIO: 5, EISDIR: 21, ELOOP: 40, EMFILE: 24, ENAMETOOLONG: 36,
  ENOENT: 2, ENOMEM: 12, ENOSYS: 38, ENOTDIR: 20, ENOTEMPTY: 39, EPERM: 1,
  EPIPE: 32, ETIMEDOUT: 110, EXDEV: 18, EMSGSIZE: 90, EPROTO: 71,
};

export const PRIORITY = {
  PRIORITY_LOW: 19, PRIORITY_BELOW_NORMAL: 10, PRIORITY_NORMAL: 0,
  PRIORITY_ABOVE_NORMAL: -7, PRIORITY_HIGH: -14, PRIORITY_HIGHEST: -20,
};

export const createConstantsBinding = () => ({
  os: {
    signals: SIGNALS,
    errno: ERRNO,
    priority: PRIORITY,
    dlopen: { RTLD_LAZY: 1, RTLD_NOW: 2, RTLD_GLOBAL: 256, RTLD_LOCAL: 0 },
    UV_UDP_REUSEADDR: 4,
  },
  fs: {},
  crypto: {},
  zlib: {},
  trace: {},
});
