// GENERATED by scripts/vendor-node-lib.mjs - do not edit.
import type { BuiltinFactory, PerContextFactory } from "./types";
import f_buffer from "./lib/buffer.js";
import f_events from "./lib/events.js";
import f_internal_assert from "./lib/internal/assert.js";
import f_internal_buffer from "./lib/internal/buffer.js";
import f_internal_constants from "./lib/internal/constants.js";
import f_internal_errors from "./lib/internal/errors.js";
import f_internal_event_target from "./lib/internal/event_target.js";
import f_internal_events_abort_listener from "./lib/internal/events/abort_listener.js";
import f_internal_options from "./lib/internal/options.js";
import f_internal_per_context_primordials from "./lib/internal/per_context/primordials.js";
import f_internal_perf_utils from "./lib/internal/perf/utils.js";
import f_internal_streams_utils from "./lib/internal/streams/utils.js";
import f_internal_util from "./lib/internal/util.js";
import f_internal_util_comparisons from "./lib/internal/util/comparisons.js";
import f_internal_util_debuglog from "./lib/internal/util/debuglog.js";
import f_internal_util_inspect from "./lib/internal/util/inspect.js";
import f_internal_util_types from "./lib/internal/util/types.js";
import f_internal_v8_startup_snapshot from "./lib/internal/v8/startup_snapshot.js";
import f_internal_validators from "./lib/internal/validators.js";
import f_internal_webidl from "./lib/internal/webidl.js";
import f_path from "./lib/path.js";
import f_util from "./lib/util.js";
import f_util_types from "./lib/util/types.js";

export const NODE_VERSION = "v24.18.0";

export const builtinFactories: Record<string, BuiltinFactory> = {
  "buffer": f_buffer,
  "events": f_events,
  "internal/assert": f_internal_assert,
  "internal/buffer": f_internal_buffer,
  "internal/constants": f_internal_constants,
  "internal/errors": f_internal_errors,
  "internal/event_target": f_internal_event_target,
  "internal/events/abort_listener": f_internal_events_abort_listener,
  "internal/options": f_internal_options,
  "internal/perf/utils": f_internal_perf_utils,
  "internal/streams/utils": f_internal_streams_utils,
  "internal/util": f_internal_util,
  "internal/util/comparisons": f_internal_util_comparisons,
  "internal/util/debuglog": f_internal_util_debuglog,
  "internal/util/inspect": f_internal_util_inspect,
  "internal/util/types": f_internal_util_types,
  "internal/v8/startup_snapshot": f_internal_v8_startup_snapshot,
  "internal/validators": f_internal_validators,
  "internal/webidl": f_internal_webidl,
  "path": f_path,
  "util": f_util,
  "util/types": f_util_types,
};

export const perContextFactories: Record<string, PerContextFactory> = {
  "internal/per_context/primordials": f_internal_per_context_primordials,
};
