// GENERATED by scripts/vendor-node-lib.mjs - do not edit.
import type { BuiltinFactory, PerContextFactory } from "./types";
import f__http_agent from "./lib/_http_agent.js";
import f__http_client from "./lib/_http_client.js";
import f__http_common from "./lib/_http_common.js";
import f__http_incoming from "./lib/_http_incoming.js";
import f__http_outgoing from "./lib/_http_outgoing.js";
import f__http_server from "./lib/_http_server.js";
import f_assert from "./lib/assert.js";
import f_async_hooks from "./lib/async_hooks.js";
import f_buffer from "./lib/buffer.js";
import f_child_process from "./lib/child_process.js";
import f_dgram from "./lib/dgram.js";
import f_diagnostics_channel from "./lib/diagnostics_channel.js";
import f_events from "./lib/events.js";
import f_fs from "./lib/fs.js";
import f_fs_promises from "./lib/fs/promises.js";
import f_http from "./lib/http.js";
import f_internal_abort_controller from "./lib/internal/abort_controller.js";
import f_internal_assert from "./lib/internal/assert.js";
import f_internal_assert_assertion_error from "./lib/internal/assert/assertion_error.js";
import f_internal_assert_calltracker from "./lib/internal/assert/calltracker.js";
import f_internal_assert_myers_diff from "./lib/internal/assert/myers_diff.js";
import f_internal_assert_utils from "./lib/internal/assert/utils.js";
import f_internal_async_context_frame from "./lib/internal/async_context_frame.js";
import f_internal_async_hooks from "./lib/internal/async_hooks.js";
import f_internal_buffer from "./lib/internal/buffer.js";
import f_internal_child_process from "./lib/internal/child_process.js";
import f_internal_child_process_serialization from "./lib/internal/child_process/serialization.js";
import f_internal_console_constructor from "./lib/internal/console/constructor.js";
import f_internal_console_global from "./lib/internal/console/global.js";
import f_internal_constants from "./lib/internal/constants.js";
import f_internal_deps_acorn_acorn_dist_acorn from "./lib/internal/deps/acorn/acorn/dist/acorn.js";
import f_internal_dgram from "./lib/internal/dgram.js";
import f_internal_errors from "./lib/internal/errors.js";
import f_internal_errors_error_source from "./lib/internal/errors/error_source.js";
import f_internal_event_target from "./lib/internal/event_target.js";
import f_internal_events_abort_listener from "./lib/internal/events/abort_listener.js";
import f_internal_fixed_queue from "./lib/internal/fixed_queue.js";
import f_internal_freelist from "./lib/internal/freelist.js";
import f_internal_fs_cp_cp from "./lib/internal/fs/cp/cp.js";
import f_internal_fs_cp_cp_sync from "./lib/internal/fs/cp/cp-sync.js";
import f_internal_fs_dir from "./lib/internal/fs/dir.js";
import f_internal_fs_glob from "./lib/internal/fs/glob.js";
import f_internal_fs_promises from "./lib/internal/fs/promises.js";
import f_internal_fs_read_context from "./lib/internal/fs/read/context.js";
import f_internal_fs_recursive_watch from "./lib/internal/fs/recursive_watch.js";
import f_internal_fs_rimraf from "./lib/internal/fs/rimraf.js";
import f_internal_fs_streams from "./lib/internal/fs/streams.js";
import f_internal_fs_sync_write_stream from "./lib/internal/fs/sync_write_stream.js";
import f_internal_fs_utils from "./lib/internal/fs/utils.js";
import f_internal_fs_watchers from "./lib/internal/fs/watchers.js";
import f_internal_http from "./lib/internal/http.js";
import f_internal_linkedlist from "./lib/internal/linkedlist.js";
import f_internal_net from "./lib/internal/net.js";
import f_internal_options from "./lib/internal/options.js";
import f_internal_per_context_primordials from "./lib/internal/per_context/primordials.js";
import f_internal_perf_utils from "./lib/internal/perf/utils.js";
import f_internal_priority_queue from "./lib/internal/priority_queue.js";
import f_internal_process_permission from "./lib/internal/process/permission.js";
import f_internal_process_promises from "./lib/internal/process/promises.js";
import f_internal_process_task_queues from "./lib/internal/process/task_queues.js";
import f_internal_process_warning from "./lib/internal/process/warning.js";
import f_internal_readline_callbacks from "./lib/internal/readline/callbacks.js";
import f_internal_readline_emitKeypressEvents from "./lib/internal/readline/emitKeypressEvents.js";
import f_internal_readline_interface from "./lib/internal/readline/interface.js";
import f_internal_readline_promises from "./lib/internal/readline/promises.js";
import f_internal_readline_utils from "./lib/internal/readline/utils.js";
import f_internal_repl_history from "./lib/internal/repl/history.js";
import f_internal_socket_list from "./lib/internal/socket_list.js";
import f_internal_source_map_source_map_cache from "./lib/internal/source_map/source_map_cache.js";
import f_internal_stream_base_commons from "./lib/internal/stream_base_commons.js";
import f_internal_streams_add_abort_signal from "./lib/internal/streams/add-abort-signal.js";
import f_internal_streams_compose from "./lib/internal/streams/compose.js";
import f_internal_streams_destroy from "./lib/internal/streams/destroy.js";
import f_internal_streams_duplex from "./lib/internal/streams/duplex.js";
import f_internal_streams_duplexpair from "./lib/internal/streams/duplexpair.js";
import f_internal_streams_end_of_stream from "./lib/internal/streams/end-of-stream.js";
import f_internal_streams_fast_utf8_stream from "./lib/internal/streams/fast-utf8-stream.js";
import f_internal_streams_from from "./lib/internal/streams/from.js";
import f_internal_streams_legacy from "./lib/internal/streams/legacy.js";
import f_internal_streams_operators from "./lib/internal/streams/operators.js";
import f_internal_streams_passthrough from "./lib/internal/streams/passthrough.js";
import f_internal_streams_pipeline from "./lib/internal/streams/pipeline.js";
import f_internal_streams_readable from "./lib/internal/streams/readable.js";
import f_internal_streams_state from "./lib/internal/streams/state.js";
import f_internal_streams_transform from "./lib/internal/streams/transform.js";
import f_internal_streams_utils from "./lib/internal/streams/utils.js";
import f_internal_streams_writable from "./lib/internal/streams/writable.js";
import f_internal_timers from "./lib/internal/timers.js";
import f_internal_util from "./lib/internal/util.js";
import f_internal_util_colors from "./lib/internal/util/colors.js";
import f_internal_util_comparisons from "./lib/internal/util/comparisons.js";
import f_internal_util_debuglog from "./lib/internal/util/debuglog.js";
import f_internal_util_inspect from "./lib/internal/util/inspect.js";
import f_internal_util_types from "./lib/internal/util/types.js";
import f_internal_v8_startup_snapshot from "./lib/internal/v8/startup_snapshot.js";
import f_internal_validators from "./lib/internal/validators.js";
import f_internal_webidl from "./lib/internal/webidl.js";
import f_internal_worker_js_transferable from "./lib/internal/worker/js_transferable.js";
import f_net from "./lib/net.js";
import f_os from "./lib/os.js";
import f_path from "./lib/path.js";
import f_readline from "./lib/readline.js";
import f_readline_promises from "./lib/readline/promises.js";
import f_stream from "./lib/stream.js";
import f_stream_promises from "./lib/stream/promises.js";
import f_string_decoder from "./lib/string_decoder.js";
import f_timers from "./lib/timers.js";
import f_timers_promises from "./lib/timers/promises.js";
import f_util from "./lib/util.js";
import f_util_types from "./lib/util/types.js";
import f_zlib from "./lib/zlib.js";

export const NODE_VERSION = "v24.18.0";

export const builtinFactories: Record<string, BuiltinFactory> = {
  "_http_agent": f__http_agent,
  "_http_client": f__http_client,
  "_http_common": f__http_common,
  "_http_incoming": f__http_incoming,
  "_http_outgoing": f__http_outgoing,
  "_http_server": f__http_server,
  "assert": f_assert,
  "async_hooks": f_async_hooks,
  "buffer": f_buffer,
  "child_process": f_child_process,
  "dgram": f_dgram,
  "diagnostics_channel": f_diagnostics_channel,
  "events": f_events,
  "fs": f_fs,
  "fs/promises": f_fs_promises,
  "http": f_http,
  "internal/abort_controller": f_internal_abort_controller,
  "internal/assert": f_internal_assert,
  "internal/assert/assertion_error": f_internal_assert_assertion_error,
  "internal/assert/calltracker": f_internal_assert_calltracker,
  "internal/assert/myers_diff": f_internal_assert_myers_diff,
  "internal/assert/utils": f_internal_assert_utils,
  "internal/async_context_frame": f_internal_async_context_frame,
  "internal/async_hooks": f_internal_async_hooks,
  "internal/buffer": f_internal_buffer,
  "internal/child_process": f_internal_child_process,
  "internal/child_process/serialization": f_internal_child_process_serialization,
  "internal/console/constructor": f_internal_console_constructor,
  "internal/console/global": f_internal_console_global,
  "internal/constants": f_internal_constants,
  "internal/deps/acorn/acorn/dist/acorn": f_internal_deps_acorn_acorn_dist_acorn,
  "internal/dgram": f_internal_dgram,
  "internal/errors": f_internal_errors,
  "internal/errors/error_source": f_internal_errors_error_source,
  "internal/event_target": f_internal_event_target,
  "internal/events/abort_listener": f_internal_events_abort_listener,
  "internal/fixed_queue": f_internal_fixed_queue,
  "internal/freelist": f_internal_freelist,
  "internal/fs/cp/cp": f_internal_fs_cp_cp,
  "internal/fs/cp/cp-sync": f_internal_fs_cp_cp_sync,
  "internal/fs/dir": f_internal_fs_dir,
  "internal/fs/glob": f_internal_fs_glob,
  "internal/fs/promises": f_internal_fs_promises,
  "internal/fs/read/context": f_internal_fs_read_context,
  "internal/fs/recursive_watch": f_internal_fs_recursive_watch,
  "internal/fs/rimraf": f_internal_fs_rimraf,
  "internal/fs/streams": f_internal_fs_streams,
  "internal/fs/sync_write_stream": f_internal_fs_sync_write_stream,
  "internal/fs/utils": f_internal_fs_utils,
  "internal/fs/watchers": f_internal_fs_watchers,
  "internal/http": f_internal_http,
  "internal/linkedlist": f_internal_linkedlist,
  "internal/net": f_internal_net,
  "internal/options": f_internal_options,
  "internal/perf/utils": f_internal_perf_utils,
  "internal/priority_queue": f_internal_priority_queue,
  "internal/process/permission": f_internal_process_permission,
  "internal/process/promises": f_internal_process_promises,
  "internal/process/task_queues": f_internal_process_task_queues,
  "internal/process/warning": f_internal_process_warning,
  "internal/readline/callbacks": f_internal_readline_callbacks,
  "internal/readline/emitKeypressEvents": f_internal_readline_emitKeypressEvents,
  "internal/readline/interface": f_internal_readline_interface,
  "internal/readline/promises": f_internal_readline_promises,
  "internal/readline/utils": f_internal_readline_utils,
  "internal/repl/history": f_internal_repl_history,
  "internal/socket_list": f_internal_socket_list,
  "internal/source_map/source_map_cache": f_internal_source_map_source_map_cache,
  "internal/stream_base_commons": f_internal_stream_base_commons,
  "internal/streams/add-abort-signal": f_internal_streams_add_abort_signal,
  "internal/streams/compose": f_internal_streams_compose,
  "internal/streams/destroy": f_internal_streams_destroy,
  "internal/streams/duplex": f_internal_streams_duplex,
  "internal/streams/duplexpair": f_internal_streams_duplexpair,
  "internal/streams/end-of-stream": f_internal_streams_end_of_stream,
  "internal/streams/fast-utf8-stream": f_internal_streams_fast_utf8_stream,
  "internal/streams/from": f_internal_streams_from,
  "internal/streams/legacy": f_internal_streams_legacy,
  "internal/streams/operators": f_internal_streams_operators,
  "internal/streams/passthrough": f_internal_streams_passthrough,
  "internal/streams/pipeline": f_internal_streams_pipeline,
  "internal/streams/readable": f_internal_streams_readable,
  "internal/streams/state": f_internal_streams_state,
  "internal/streams/transform": f_internal_streams_transform,
  "internal/streams/utils": f_internal_streams_utils,
  "internal/streams/writable": f_internal_streams_writable,
  "internal/timers": f_internal_timers,
  "internal/util": f_internal_util,
  "internal/util/colors": f_internal_util_colors,
  "internal/util/comparisons": f_internal_util_comparisons,
  "internal/util/debuglog": f_internal_util_debuglog,
  "internal/util/inspect": f_internal_util_inspect,
  "internal/util/types": f_internal_util_types,
  "internal/v8/startup_snapshot": f_internal_v8_startup_snapshot,
  "internal/validators": f_internal_validators,
  "internal/webidl": f_internal_webidl,
  "internal/worker/js_transferable": f_internal_worker_js_transferable,
  "net": f_net,
  "os": f_os,
  "path": f_path,
  "readline": f_readline,
  "readline/promises": f_readline_promises,
  "stream": f_stream,
  "stream/promises": f_stream_promises,
  "string_decoder": f_string_decoder,
  "timers": f_timers,
  "timers/promises": f_timers_promises,
  "util": f_util,
  "util/types": f_util_types,
  "zlib": f_zlib,
};

export const perContextFactories: Record<string, PerContextFactory> = {
  "internal/per_context/primordials": f_internal_per_context_primordials,
};
