/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorRouteImport } from './routes/_editor'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as EditorEditorIdRouteImport } from './routes/_editor/editor/$id'

const EditorRoute = EditorRouteImport.update({
  id: '/_editor',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const EditorEditorIdRoute = EditorEditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => EditorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/editor/$id': typeof EditorEditorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/editor/$id': typeof EditorEditorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_editor': typeof EditorRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_editor/editor/$id': typeof EditorEditorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor/$id'
  id: '__root__' | '/_editor' | '/_main' | '/_main/' | '/_editor/editor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EditorRoute: typeof EditorRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_editor': {
      id: '/_editor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_editor/editor/$id': {
      id: '/_editor/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorEditorIdRouteImport
      parentRoute: typeof EditorRoute
    }
  }
}

interface EditorRouteChildren {
  EditorEditorIdRoute: typeof EditorEditorIdRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorEditorIdRoute: EditorEditorIdRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  EditorRoute: EditorRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
